services:
  - type: web
    name: clubs-network-api
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clubs-network-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_TOKEN_TTL
        value: 15m
      - key: JWT_REFRESH_TOKEN_TTL
        value: 7d
      - key: NODE_ENV
        value: production
      - key: COOKIE_DOMAIN
        value: ".onrender.com"
      - key: CLIENT_URL
        value: "http://138.68.94.59/ "

databases:
  - name: clubs-network-db
    plan: free
    databaseName: clubs_network